#!/usr/bin/env node
/**
 * VRC Chatbox OSC — UI build (single step).
 *
 * Reads the human-edited sources in src/, minifies (esbuild) and merges
 * everything into a single embedded page, then writes the FASM include file.
 *
 * Outputs (dist/ — generated, not committed):
 *   dist/index.html   — the final single-file page served by the exe
 *   dist/html.inc     — FASM `file` include used by ../server.asm
 */
const fs = require('fs');
const path = require('path');
const esbuild = require('esbuild');

const SRC = path.join(__dirname, 'src');
const DIST = path.join(__dirname, 'dist');
const OUT_HTML = path.join(DIST, 'index.html');
const OUT_INC = path.join(DIST, 'html.inc');

// ---- helpers -----------------------------------------------------------

function minifyCss(css) {
  return css
    .replace(/\/\*.*?\*\//gs, '')
    .replace(/\s+/g, ' ')
    .replace(/\s*([{}:;,])\s*/g, '$1')
    .trim();
}

// Full minification (name mangling) via esbuild. app.js is wrapped in an
// IIFE so esbuild can rename every internal identifier; the handful of
// window-exposed handlers (startLongPress, ...) keep their names.
async function minifyJsFull(js) {
  const { code } = await esbuild.transform(js, { minify: true });
  return code.trim();
}

// ---- merge step ---------------------------------------------------------

async function merge() {
  const tpl = fs.readFileSync(path.join(SRC, 'template.html'), 'utf8');
  const css = fs.readFileSync(path.join(SRC, 'style.css'), 'utf8');
  const js = fs.readFileSync(path.join(SRC, 'app.js'), 'utf8');

  // No vendored libs — app.js is self-contained and esbuild handles
  // everything; keep this simple on purpose.

  const cssFull = css;
  const jsFull = js;

  const minJs = await minifyJsFull(jsFull);
  const html = tpl
    .replace('/*STYLE*/', () => minifyCss(cssFull))
    .replace('/*SCRIPT*/', () => minJs);
  fs.writeFileSync(OUT_HTML, html, 'utf8');
  return html;
}

// ---- fasam include step --------------------------------------------------

function writeInc(html) {
  // html.inc sits in ui/dist/, referenced by ../server.asm via include.
  // The `file` path is relative to server.asm (native-asm/), so it must be
  // 'ui/dist/index.html'.
  const rel = path.relative(path.join(__dirname, '..'), OUT_HTML).replace(/\\/g, '/');
  const inc = [
    '; generated by ui/build.js from ui/src/ -- do not edit.',
    `html file '${rel}'`,
    '',
  ].join('\n');
  fs.writeFileSync(OUT_INC, inc, 'utf8');
}

// ---- main ---------------------------------------------------------------

async function main() {
  if (!fs.existsSync(DIST)) fs.mkdirSync(DIST, { recursive: true });

  const html = await merge();
  writeInc(html);

  const raw = Buffer.byteLength(html, 'utf8');
  console.log(`ui/build: index.html ${raw} B`);
}

main().catch((err) => {
  console.error('ui/build: ERROR', err.message);
  process.exit(1);
});
